# -*- coding: utf-8 -*-
"""lane_detection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LUNu9-jqu_69dt6h_PevhG-ArvTOQnWX
"""

import cv2
import numpy as np

def grayscale(img):
    return cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

def canny(img, low_threshold=50, high_threshold=150):
    return cv2.Canny(img, low_threshold, high_threshold)

def gaussian_blur(img, kernel_size=5):
    return cv2.GaussianBlur(img, (kernel_size, kernel_size), 0)

def region_of_interest(img):
    height = img.shape[0]
    width = img.shape[1]
    polygons = np.array([[
        (int(0.1 * width), height),
        (int(0.45 * width), int(0.6 * height)),
        (int(0.55 * width), int(0.6 * height)),
        (int(0.9 * width), height)
    ]])
    mask = np.zeros_like(img)
    cv2.fillPoly(mask, polygons, 255)
    return cv2.bitwise_and(img, mask)

def display_lines(img, lines):
    line_image = np.zeros_like(img)
    if lines is not None:
        for line in lines:
            for x1, y1, x2, y2 in line:
                cv2.line(line_image, (x1, y1), (x2, y2), (255, 0, 0), 10)
    return line_image

def make_coordinates(img, line_parameters):
    slope, intercept = line_parameters
    y1 = img.shape[0]
    y2 = int(y1 * 0.6)
    x1 = int((y1 - intercept)/slope)
    x2 = int((y2 - intercept)/slope)
    return np.array([x1, y1, x2, y2])

def average_slope_intercept(img, lines):
    left_fit = []
    right_fit = []

    for line in lines:
        for x1, y1, x2, y2 in line:
            parameters = np.polyfit((x1, x2), (y1, y2), 1)
            slope, intercept = parameters

            if slope < 0:
                left_fit.append((slope, intercept))
            else:
                right_fit.append((slope, intercept))

    averaged_lines = []
    if left_fit:
        left_avg = np.average(left_fit, axis=0)
        averaged_lines.append([make_coordinates(img, left_avg)])
    if right_fit:
        right_avg = np.average(right_fit, axis=0)
        averaged_lines.append([make_coordinates(img, right_avg)])

    return averaged_lines

# Set up video capture and output writer
cap = cv2.VideoCapture('solidWhiteRight.mp4')

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter('lane_detected_output.mp4', fourcc, 20.0,
                      (int(cap.get(3)), int(cap.get(4))))

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    gray = grayscale(frame)
    blur = gaussian_blur(gray)
    edges = canny(blur)

    cropped = region_of_interest(edges)
    lines = cv2.HoughLinesP(cropped, 2, np.pi/180, 100,
                            np.array([]), minLineLength=40, maxLineGap=5)
    averaged_lines = average_slope_intercept(frame, lines)
    line_img = display_lines(frame, averaged_lines)

    combo = cv2.addWeighted(frame, 0.8, line_img, 1, 1)
    out.write(combo)

cap.release()
out.release()
cv2.destroyAllWindows()
print("✅ Processing complete. Output video saved as lane_detected_output.mp4")